---
title: "Eksploracja_1"
output: html_document
date: "2026-02-23"
---

## R Markdown

```{r}
rm(list = ls())  # Clears the environment
```

```{r pressure}
library(titanic)
titanic_test
titanic_train
titanic_gender_class_model
```

```{r pressure}
# Load necessary library
library(dplyr)
library(tidyr)

# Clean the data frame
titanic_cleaned <- titanic_train %>%
  # Remove unnecessary columns
  select(-PassengerId, -Name, -Ticket, -Cabin) %>%
  # Replace empty strings in 'Embarked' with NA
  mutate(Embarked = na_if(Embarked, "")) %>%
  # Drop rows with missing values
  drop_na() %>%
  # Convert 'Sex' and 'Embarked' to factors
  mutate(Sex = as.factor(Sex),
         Embarked = as.factor(Embarked))

# View the cleaned data
str(titanic_cleaned)
```

```{r}
titanic_data <- titanic_train
titanic_data
```

```{r}
titanic_data <- titanic_data[, -c(1,4,9)]
titanic_data
```

```{r}
titanic_data[titanic_data== ""] <-NA
titanic_data
```

```{r}
colSums(is.na(titanic_data))
```

```{r}
titanic_data <- titanic_data[, -c(8)]
titanic_data
```

```{r}
titanic_data <- na.omit(titanic_data)
titanic_data
```

```{r}
titanic_data$Sex <- ifelse(titanic_data$Sex == "male", 1, 0)
titanic_data
```

```{r}
# Example data frame
# One-hot encoding for the 'Sex' column
one_hot <- model.matrix(~ Embarked - 1, data = titanic_data)

# Combine the one-hot encoded columns with the original data
titanic_data <- cbind(titanic_data, one_hot)
titanic_data <- titanic_data[, -c(8)]
titanic_data
```

```{r}
titanic_data$Pclass <- as.factor(titanic_data$Pclass)
one_hot <- model.matrix(~ Pclass - 1, data = titanic_data)
one_hot

titanic_data <- cbind(titanic_data, one_hot)
titanic_data
titanic_data <- titanic_data[, -c(2)]
titanic_data
```

```{r}
titanic_data$SibSp <- ifelse(titanic_data$SibSp == 0, 0, 
                        ifelse(titanic_data$SibSp == 1, 1, 2))
titanic_data
```

```{r}
titanic_data$Parch <- ifelse(titanic_data$Parch == 0, 0, 
                        ifelse(titanic_data$Parch == 1, 1, 2))
titanic_data
```

```{r}

```

```{r}
titanic_data$SibSp <- as.factor(titanic_data$SibSp)
one_hot <- model.matrix(~ SibSp - 1, data = titanic_data)
one_hot

titanic_data <- cbind(titanic_data, one_hot)
titanic_data
titanic_data <- titanic_data[, -c(4)]
titanic_data
```

```{r}
titanic_data$Parch <- as.factor(titanic_data$Parch)
one_hot <- model.matrix(~ Parch - 1, data = titanic_data)
one_hot

titanic_data <- cbind(titanic_data, one_hot)
titanic_data
titanic_data <- titanic_data[, -c(4)]
titanic_data
```

```{r}
# Split the data: 70% training, 30% testing
library(caret)
trainIndex <- createDataPartition(titanic_data$Survived, p = 0.8)

# Create training and testing datasets
trainData <- titanic_data[trainIndex, ]
testData <- titanic_data[-trainIndex, ]

# Check the dimensions of the datasets
dim(trainData)
dim(testData)
```

```{r}
# Create a logistic regression model
logistic_model <- glm(Survived ~ ., data = trainData, family = binomial)

# Summary of the model
summary(logistic_model)

# Make predictions on the test data
predictions <- predict(logistic_model, newdata = testData, type = "response")


```

```{r}

```
